#!/usr/bin/env bash
# Transfer a file from our client to a server
#
# variables
path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
filename=$(basename "${BASH_SOURCE[0]}")
brown='\e[0;33m'
reset='\033[0m'
file="$1"      # $1 is the first argument (file path)
ip="$2"        # $2 is the second argument (IP address)
user="ubuntu"
key="~/.ssh/id_rsa"  # Path to SSH key

# Check if the number of arguments is 2 (file and IP)
if [ "$#" -eq 2 ]; then
    scp -i "$key" -o StrictHostKeyChecking=no "$file" "$user@$ip:/home/$user/"
else
    echo -e "Usage: ${brown}${filename} PATH_TO_FILE IP_ADDRESS${reset}"
fi

